### ISSUE TITLE
Can't load shared library

### ISSUE THREAD

**Issue by antony** [cathive/sass-java#2]
Hi.

I've got this running fine at home, gradle build, dependencies are there and classes are found. Same at home, however when I run my tests I get this.

java.lang.UnsatisfiedLinkError: Unable to load library 'sass': libsass.so: cannot open shared object file: No such file or directory
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:163)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:236)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:199)
    at com.cathive.sass.jna.SassLibrary.<clinit>(SassLibrary.java:19)
    at com.cathive.sass.SassFileContext.create(SassFileContext.java:47)
    at CompilationSpec.Sass compilation failure throws exception(CompilationSpec.groovy:16)

The machine is the same configuration - Linux x86 - 64 Bit. I've literally checked out my project and built it. Same JVM, Same Gradle version, same buildfile.

I can't figure it out for the life of me. Is this a bug or am I missing something obvious?

**Comment by headcr4sh** [comment]
Hi Antony,

I suggest you have a closer look at the pre-compiled library:

``` sh
ldd src/main/resources/linux-x86-64/libsass.so
```

What's the output?

**Comment by headcr4sh** [comment]
I thought a bit more about your issue.
The error message clearly indicates, that libsass.so cannot be found at all. Maybe you are NOT using a 64 bit Java Virtual Machine. So... I suggest to check your environment:

  1) What is your `${JAVA_HOME}`
  2) What´s the output of `java -version`

**Comment by antony** [comment]
Hi @headcr4sh 

Thanks for taking a look at my issue.

The information you have asked for is:

```
echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
```

and:

```
java -version
openjdk version "1.8.0_40-internal"
OpenJDK Runtime Environment (build 1.8.0_40-internal-b09)
OpenJDK 64-Bit Server VM (build 25.40-b13, mixed mode)
```

Looks like it is 64-bit to me. It's an Ubuntu 14.10 Install using the default jdk8 package from the ubuntu repositories.

I've got a very similar set-up on a Dell desktop at my client, and that seems to pick it up fine.

Output from ldd is:

```
ldd src/main/resources/linux-x86-64/libsass.so
    linux-vdso.so.1 =>  (0x00007ffffa71c000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f12216f7000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f12213f1000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f12211d9000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1220e15000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f1221d9f000)
```

Cheers,
Antony

**Comment by headcr4sh** [comment]
Really strange.

I have just updated the upstream library to the latest libsass version.
Would you like to give the latest sources a try? (A release to Maven Central has not yet been performed)

Attention:
The artifactId has changed (I dropped defunct OSGi support).

**Comment by antony** [comment]
Sure - I'll give it a go asap!

**Comment by headcr4sh** [comment]
No reply. I hope, the issue has been solved in the latest version of sass-java.
