### ISSUE TITLE
Upload the artifact to Maven central

### ISSUE THREAD

**Issue by szgabsz91** [cathive/sass-java#3]
Hi!

First of all I'm very glad that I've found this library as this is the only one that contains x86 compatible shared libraries.

Unfortunately Maven central does not contain the latest version (http://search.maven.org/#search%7Cga%7C1%7Ccom.cathive.sass) and the uploaded version only comes with x64 libraries.

Could you please upload a version that has all the libraries so that I can use your project without forking it?

Thank you in advanced and keep up the good work!

**Comment by szgabsz91** [comment]
Sorry for writing again, but I see that a new tag was released on Github a couple of days ago. Is this release going to become available through the Maven central repository? Because I still don't see it, nor can I use it.

It's not very urgent so I can wait for it, just asking! :)

**Comment by headcr4sh** [comment]
I'm still searching for my GPG key ... I plan to perform the release to Maven central in the next few days....

**Comment by headcr4sh** [comment]
Version 3.2.5.0 (which conains bundled version of libsass v3.2.5) has just been released to the Sonatype OSS Maven repository. It usually takes a few hours until the artifact has been pushed to Maven Central.

Please make sure that you use the new artifact coordinates:

``` xml
<dependency>
  <groupId>com.cathive.sass</groupId>
  <artifactId>sass-java</artifactId>
  <version>3.2.5.0</version>
</dependency>
```

**Comment by szgabsz91** [comment]
Thank you very much, I tested it and works fine!
