### ISSUE TITLE
Typo in SassOptions API?

### ISSUE THREAD

**Issue by ricksbrown** [cathive/sass-java#5]
Hi again @headcr4sh 

Just FYI, while I was working on the Ant task I noticed [SassOptions.setPrecission](https://github.com/cathive/sass-java/blob/464898df960a6ddf20500eef2bad6eb9743a57ef/src/main/java/com/cathive/sass/SassOptions.java#L68) and [SassOptions.getPrecission](https://github.com/cathive/sass-java/blob/464898df960a6ddf20500eef2bad6eb9743a57ef/src/main/java/com/cathive/sass/SassOptions.java#L72) which should probably be `SassOptions.setPrecision` and `SassOptions.getPrecision` respectively (single 's' not double 'ss').

Obviously no big deal, just thought I'd let you know.

**Comment by headcr4sh** [comment]
Oh damn. You're right, of course... Thanks for the information. I'll fix that typo before the next release is pushed out of the door. (Want to provide another PR?) ;-)

**Comment by headcr4sh** [comment]
Notice:
I am not a native speaker, so I might have put a whole lot of typos and grammatical oddities into the sources and their documentation. Feel free to suggest corrections and improvements if you stumble across stuff that seems weird.

**Comment by ricksbrown** [comment]
I'd be happy to open a PR for this and I'll give it a quick once-over for anything similar.

BTW I was wondering if you had an idea of when you will push your next release to Maven Central?

**Comment by ricksbrown** [comment]
Oops I found some issues in (what I added to) the README file, I'll fix them too and maybe add a couple more unit tests for the Ant task.
